version: '3'
services:
  web:
    build: ./nginx  #Pointer to Dockerfile directory
    ports:
     - "8087:80"
  db:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb